In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("data_set.csv")
df

Match no. team 1 team 2  runs 1  runs 2    stadium  Overs left  \
0           1     MI    CSK     162     166  ABU DHABI           4   
1           2     DC   PBKS     157     157      DUBAI           0   
2           3    RCB    SRH     163     153      DUBAI           2   
3           4     RR    CSK     216     200    SHARJAH           0   
4           5     MI    KKR     195     146  ABU DHABI           0   
5           6   PBKS    RCB     206     109      DUBAI          18   
6           7     DC    CSK     175     131      DUBAI           0   
7           8    SRH    KKR     142     145  ABU DHABI          12   
8           9   PBKS     RR     223     226    SHARJAH           3   
9          10    RCB     MI     201     201      DUBAI           0   
10         11    SRH     DC     162     147  ABU DHABI           0   
11         12    KKR     RR     174     137      DUBAI           0   
12         13     MI   PBKS     191     143  ABU DHABI           0   
13         14    SRH    CSK     164     157      DUBAI           0   
14         15     RR    RCB     154     158  ABU DHABI           5   
15         16     DC    KKR     228     210    SHARJAH           0   
16         17     MI    SRH     208     174    SHARJAH           0   
17         18   PBKS    CSK     178     181      DUBAI          14   
18         19     DC    RCB     196     137      DUBAI           0   
19         20     MI     RR     193     136  ABU DHABI          11   
20         21    KKR    CSK     167     157  ABU DHABI           0   
21         22    SRH   PBKS     201     132      DUBAI          19   
22         23     DC     RR     184     138  ABU DHABI           2   
23         24    KKR   PBKS     164     162  ABU DHABI           0   
24         25    RCB    CSK     169     132      DUBAI           0   
25         26    SRH     RR     158     163      DUBAI           1   
26         27     DC     MI     162     166  ABU DHABI           2   
27         28    RCB    KKR     194     112    SHARJAH           0   
28         29    CSK    SRH     167     147      DUBAI           0   
29         30     DC     RR     161     148      DUBAI           0   
30         31    RCB   PBKS     171     177    SHARJAH           0   
31         32    KKR     MI     148     149  ABU DHABI          19   
32         33     RR    RCB     177     179      DUBAI          12   
33         34    CSK     DC     179     185    SHARJAH           6   
34         35    KKR    SRH     163     163  ABU DHABI           0   
35         36     MI   PBKS     176     176      DUBAI           0   
36         37    CSK     RR     125     126  ABU DHABI          15   
37         38     DC   PBKS     164     167      DUBAI           6   
38         39    KKR    RCB      84      85  ABU DHABI          39   
39         40     RR    SRH     154     156      DUBAI          11   
40         41    CSK     MI     114     116    SHARJAH          46   
41         42    KKR     DC     194     135  ABU DHABI           0   
42         43   PBKS    SRH     126     114      DUBAI           1   
43         44    RCB    CSK     145     150      DUBAI           8   
44         45     MI     RR     195     196  ABU DHABI          10   
45         46    KKR   PBKS     149     150    SHARJAH           7   
46         47    SRH     DC     219     131      DUBAI           6   
47         48    RCB     MI     164     166  ABU DHABI           5   
48         49    KKR    CSK     172     178      DUBAI           0   
49         50   PBKS     RR     185     186  ABU DHABI          15   
50         51     DC     MI     110     111      DUBAI          34   
51         52    RCB    SRH     120     121    SHARJAH          35   
52         53   PBKS    CSK     153     154  ABU DHABI           7   
53         54    KKR     RR     191     131      DUBAI           0   
54         55    RCB     DC     152     154  ABU DHABI           6   
55         56     MI    SRH     149     151    SHARJAH          17   
56         57 

In [3]:
teams = df["team 1"].unique()
teams

array(['MI', 'DC', 'RCB', 'RR', 'PBKS', 'SRH', 'KKR', 'CSK'], dtype=object)

In [4]:
dit = {}
for i in teams:
    a = df[df["team 1"] == i]
    dit[i] = [a["runs 1"].mean(),a["runs 1"].sum()/a["runs 1"].mean()]
    

In [5]:
dit #averages of teams batting 1st, no. of matches played

{'MI': [185.44444444444446, 9.0],
 'DC': [171.0909090909091, 11.0],
 'RCB': [161.0, 10.0],
 'RR': [175.25, 4.0],
 'PBKS': [178.5, 6.0],
 'SRH': [174.33333333333334, 6.0],
 'KKR': [160.6, 10.0],
 'CSK': [146.25, 4.0]}

In [6]:
dit2 = {}
for i in teams:
    a = df[df["team 2"] == i]
    dit2[i] = [a["runs2_projected"].mean(),a["runs2_projected"].sum()/a["runs2_projected"].mean()]
    

In [7]:
dit2  #averages of teams batting 2nd, no. of matches played

{'MI': [175.85714285714286, 7.0],
 'DC': [153.33333333333334, 6.0],
 'RCB': [151.0, 5.0],
 'RR': [167.3, 10.0],
 'PBKS': [163.375, 8.0],
 'SRH': [158.0, 10.0],
 'KKR': [157.25, 4.0],
 'CSK': [165.7, 10.0]}

In [8]:
dit.keys()

dict_keys(['MI', 'DC', 'RCB', 'RR', 'PBKS', 'SRH', 'KKR', 'CSK'])

In [9]:
dit['MI'][0]

185.44444444444446

In [10]:
teams_avg = {}
for i in teams:
    teams_avg[i] = ((dit[i][0]*dit[i][1])+(dit2[i][0]*dit2[i][1]))/(dit[i][1]+dit2[i][1])

In [11]:
teams_avg

{'MI': 181.25,
 'DC': 164.8235294117647,
 'RCB': 157.66666666666666,
 'RR': 169.57142857142858,
 'PBKS': 169.85714285714286,
 'SRH': 164.125,
 'KKR': 159.64285714285714,
 'CSK': 160.14285714285714}

In [12]:
pitch_avg = {}
pitches = df['stadium'].unique()
pitches

array(['ABU DHABI', 'DUBAI', 'SHARJAH'], dtype=object)

In [13]:
for i in pitches:
    df_pitch = df[df["stadium"] == i]
    pitch_avg[i]  = df_pitch['runs 1'].mean()
   

In [14]:
pitch_avg

{'ABU DHABI': 163.43478260869566,
 'DUBAI': 171.53846153846155,
 'SHARJAH': 177.36363636363637}

In [15]:
bowling_average = {}
for i in teams:
    df_bowlings = df[df["team 2"] == i]
    bowling_average[i] = [df_bowlings['runs 1'].mean(),df_bowlings['runs 1'].sum()/df_bowlings['runs 1'].mean()]

In [16]:
bowling_average

{'MI': [150.71428571428572, 7.0],
 'DC': [184.33333333333334, 6.0],
 'RCB': [163.4, 5.0],
 'RR': [178.9, 10.0],
 'PBKS': [171.625, 8.0],
 'SRH': [157.0, 10.0],
 'KKR': [189.75, 4.0],
 'CSK': [170.1, 10.0]}

In [17]:
bowling_average_2 = {}
for i in teams:
    df_bowlings = df[df["team 1"] == i]
    bowling_average_2[i] = [df_bowlings['runs 2'].mean(),df_bowlings['runs 2'].sum()/df_bowlings['runs 2'].mean()]

In [18]:
bowling_average_2

{'MI': [159.0, 9.0],
 'DC': [154.0, 11.0],
 'RCB': [149.8, 10.0],
 'RR': [173.25, 4.0],
 'PBKS': [161.66666666666666, 6.0],
 'SRH': [145.83333333333334, 6.0],
 'KKR': [144.7, 10.0],
 'CSK': [143.5, 4.0]}

In [19]:
bowling_avg = {}
for i in teams:
    bowling_avg[i] = ((bowling_average[i][0]*bowling_average[i][1])+(bowling_average_2[i][0]*bowling_average_2[i][1]))/(bowling_average[i][1]+bowling_average_2[i][1])

In [20]:
bowling_avg

{'MI': 155.375,
 'DC': 164.7058823529412,
 'RCB': 154.33333333333334,
 'RR': 177.28571428571428,
 'PBKS': 167.35714285714286,
 'SRH': 152.8125,
 'KKR': 157.57142857142858,
 'CSK': 162.5}

In [21]:
df_pr = pd.read_excel("predict.xlsx")
df_pr

team1 team2  runs1    stadium  batting_avg  bowling_avg  pitch_avg
0     MI   CSK    162  ABU DHABI      181.250       162.50     163.43
1     DC  PBKS    157      DUBAI      164.820       167.36     171.54
2    RCB   SRH    163      DUBAI      157.670       152.81     171.54
3     RR   CSK    216    SHARJAH      169.570       162.50     177.36
4     MI   KKR    195  ABU DHABI      181.250       157.57     163.43
5   PBKS   RCB    206      DUBAI      169.860       154.33     171.54
6     DC   CSK    175      DUBAI      164.820       162.50     171.54
7    SRH   KKR    142  ABU DHABI      164.125       157.57     163.43
8   PBKS    RR    223    SHARJAH      169.860       177.28     177.36
9    RCB    MI    201      DUBAI      157.670       155.37     171.54
10   SRH    DC    162  ABU DHABI      164.125       164.70     163.43
11   KKR    RR    174      DUBAI      159.640       177.28     171.54
12    MI  PBKS    191  ABU DHABI      181.250       167.36     163.43
13   SRH   CSK    164      DUBAI      164.125       162.50     171.54
14    RR   RCB    154  ABU DHABI      169.570       154.33     163.43
15    DC   KKR    228    SHARJAH      164.820       157.57     177.36
16    MI   SRH    208    SHARJAH      181.250       152.81     177.36
17  PBKS   CSK    178      DUBAI      169.860       162.50     171.54
18    DC   RCB    196      DUBAI      164.820       154.33     171.54
19    MI    RR    193  ABU DHABI      181.250       177.28     163.43
20   KKR   CSK    167  ABU DHABI      159.640       162.50     163.43
21   SRH  PBKS    201      DUBAI      164.125       167.36     171.54
22    DC    RR    184  ABU DHABI      164.820       177.28     163.43
23   KKR  PBKS    164  ABU DHABI      159.640       167.36     163.43
24   RCB   CSK    169      DUBAI      157.670       162.50     171.54
25   SRH    RR    158      DUBAI      164.125       177.28     171.54
26    DC    MI    162  ABU DHABI      164.820       155.37     163.43
27   RCB   KKR    194    SHARJAH      157.670       157.57     177.36
28   CSK   SRH    167      DUBAI      160.140       152.81     171.54
29    DC    RR    161      DUBAI      164.820       177.28     171.54
30   RCB  PBKS    171    SHARJAH      157.670       167.36     177.36
31   KKR    MI    148  ABU DHABI      159.640       155.37     163.43
32    RR   RCB    177      DUBAI      169.570       154.33     171.54
33   CSK    DC    179    SHARJAH      160.140       164.70     177.36
34   KKR   SRH    163  ABU DHABI      159.640       152.81     163.43
35    MI  PBKS    176      DUBAI      181.250       167.36     171.54
36   CSK    RR    125  ABU DHABI      160.140       177.28     163.43
37    DC  PBKS    164      DUBAI      164.820       167.36     171.54
38   KKR   RCB     84  ABU DHABI      159.640       154.33     163.43
39    RR   SRH    154      DUBAI      169.570       152.81     171.54
40   CSK    MI    114    SHARJAH      160.140       155.37     177.36
41   KKR    DC    194  ABU DHABI      159.640       164.70     163.43
42  PBKS   SRH    126      DUBAI      169.860       152.81     171.54
43   RCB   CSK    145      DUBAI      157.670       162.50     171.54
44    MI    RR    195  ABU DHABI      181.250       177.28     163.43
45   KKR  PBKS    149    SHARJAH      159.640       167.36     177.36
46   SRH    DC    219      DUBAI      164.125       164.70     171.54
47   RCB    MI    164  ABU DHABI      157.670       155.37     163.43
48   KKR   CSK    172      DUBAI      159.640       162.50     171.54
49  PBKS    RR    185  ABU DHABI      169.860       177.28     163.43
50    DC    MI    110      DUBAI      164.820       155.37     171.54
51   RCB   SRH    120    SHARJAH      157.670       152.81     177.36
52  PBKS   CSK    153  ABU DHABI      169.860       162.50     163.43
53   KKR    RR    191      DUBAI      159.640       177.28     171.54
54   RCB    DC    152  ABU DHABI      157.670       164.70     163.43
55    MI   SRH    149    SHARJAH      181.250       152.81     177.36
56    MI    D

In [22]:
import sklearn
from sklearn.linear_model import LinearRegression as lr
from sklearn.model_selection import train_test_split

In [23]:
x = df_pr.drop(columns=['team1','team2','stadium','runs1'],axis =1)
y = df_pr["runs1"]

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [25]:
x_train

batting_avg  bowling_avg  pitch_avg
46      164.125       164.70     171.54
3       169.570       162.50     177.36
26      164.820       155.37     163.43
36      160.140       177.28     163.43
21      164.125       167.36     171.54
10      164.125       164.70     163.43
52      169.860       162.50     163.43
19      181.250       177.28     163.43
42      169.860       152.81     171.54
56      181.250       164.70     171.54
17      169.860       162.50     171.54
31      159.640       155.37     163.43
49      169.860       177.28     163.43
32      169.570       154.33     171.54
47      157.670       155.37     163.43
38      159.640       154.33     163.43
55      181.250       152.81     177.36
13      164.125       162.50     171.54
22      164.820       177.28     163.43
51      157.670       152.81     177.36
30      157.670       167.36     177.36
34      159.640       152.81     163.43
23      159.640       167.36     163.43
4       181.250       157.57     163.43
14      169.570       154.33     163.43
29      164.820       177.28     171.54
28      160.140       152.81     171.54
54      157.670       164.70     163.43
58      164.820       152.81     163.43
18      164.820       154.33     171.54
59      164.820       155.37     171.54
20      159.640       162.50     163.43
25      164.125       177.28     171.54
6       164.820       162.50     171.54
45      159.640       167.36     177.36
7       164.125       157.57     163.43
57      157.670       152.81     163.43
1       164.820       167.36     171.54
16      181.250       152.81     177.36
0       181.250       162.50     163.43
15      164.820       157.57     177.36
5       169.860       154.33     171.54
11      159.640       177.28     171.54
9       157.670       155.37     171.54
8       169.860       177.28     177.36
12      181.250       167.36     163.43
43      157.670       162.50     171.54
37      164.820       167.36     171.54

In [26]:
model = lr()
model.fit(x_train,y_train)

LinearRegression()

In [27]:
y_predict = model.predict(x_test)
y_predict

array([173.7587101 , 153.24825336, 156.8557428 , 165.11240075,
       168.45379084, 191.02986394, 176.46532401, 198.54528862,
       171.20967856, 168.94052084, 162.31417843, 173.43806417])

In [28]:
from sklearn.metrics import r2_score

In [29]:
r2scoreof_runs1 = r2_score(y_test, y_predict)

In [30]:
r2scoreof_runs1

-0.11027427821637792

In [31]:
y_test

39    154
41    194
2     163
48    172
50    110
44    195
33    179
35    176
40    114
27    194
24    169
53    191
Name: runs1, dtype: int64

In [32]:
y_predict

array([173.7587101 , 153.24825336, 156.8557428 , 165.11240075,
       168.45379084, 191.02986394, 176.46532401, 198.54528862,
       171.20967856, 168.94052084, 162.31417843, 173.43806417])

In [33]:
model.coef_

array([1.42041742, 0.56330605, 1.61571155])

In [34]:
from sklearn.tree import DecisionTreeRegressor as dtr

In [35]:
model_dt = dtr(max_depth=4)

In [36]:
model_dt.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=4)

In [37]:
y_predict_dt  = model_dt.predict(x_test)

In [38]:
model_dt.score(x_test,y_predict_dt)

1.0

In [39]:
y_predict_dt

array([167.53846154, 160.28571429, 125.5       , 160.28571429,
       167.53846154, 194.66666667, 125.        , 194.66666667,
       125.        , 171.        , 160.28571429, 160.28571429])

In [40]:
y_test

39    154
41    194
2     163
48    172
50    110
44    195
33    179
35    176
40    114
27    194
24    169
53    191
Name: runs1, dtype: int64

In [41]:
df_pr

team1 team2  runs1    stadium  batting_avg  bowling_avg  pitch_avg
0     MI   CSK    162  ABU DHABI      181.250       162.50     163.43
1     DC  PBKS    157      DUBAI      164.820       167.36     171.54
2    RCB   SRH    163      DUBAI      157.670       152.81     171.54
3     RR   CSK    216    SHARJAH      169.570       162.50     177.36
4     MI   KKR    195  ABU DHABI      181.250       157.57     163.43
5   PBKS   RCB    206      DUBAI      169.860       154.33     171.54
6     DC   CSK    175      DUBAI      164.820       162.50     171.54
7    SRH   KKR    142  ABU DHABI      164.125       157.57     163.43
8   PBKS    RR    223    SHARJAH      169.860       177.28     177.36
9    RCB    MI    201      DUBAI      157.670       155.37     171.54
10   SRH    DC    162  ABU DHABI      164.125       164.70     163.43
11   KKR    RR    174      DUBAI      159.640       177.28     171.54
12    MI  PBKS    191  ABU DHABI      181.250       167.36     163.43
13   SRH   CSK    164      DUBAI      164.125       162.50     171.54
14    RR   RCB    154  ABU DHABI      169.570       154.33     163.43
15    DC   KKR    228    SHARJAH      164.820       157.57     177.36
16    MI   SRH    208    SHARJAH      181.250       152.81     177.36
17  PBKS   CSK    178      DUBAI      169.860       162.50     171.54
18    DC   RCB    196      DUBAI      164.820       154.33     171.54
19    MI    RR    193  ABU DHABI      181.250       177.28     163.43
20   KKR   CSK    167  ABU DHABI      159.640       162.50     163.43
21   SRH  PBKS    201      DUBAI      164.125       167.36     171.54
22    DC    RR    184  ABU DHABI      164.820       177.28     163.43
23   KKR  PBKS    164  ABU DHABI      159.640       167.36     163.43
24   RCB   CSK    169      DUBAI      157.670       162.50     171.54
25   SRH    RR    158      DUBAI      164.125       177.28     171.54
26    DC    MI    162  ABU DHABI      164.820       155.37     163.43
27   RCB   KKR    194    SHARJAH      157.670       157.57     177.36
28   CSK   SRH    167      DUBAI      160.140       152.81     171.54
29    DC    RR    161      DUBAI      164.820       177.28     171.54
30   RCB  PBKS    171    SHARJAH      157.670       167.36     177.36
31   KKR    MI    148  ABU DHABI      159.640       155.37     163.43
32    RR   RCB    177      DUBAI      169.570       154.33     171.54
33   CSK    DC    179    SHARJAH      160.140       164.70     177.36
34   KKR   SRH    163  ABU DHABI      159.640       152.81     163.43
35    MI  PBKS    176      DUBAI      181.250       167.36     171.54
36   CSK    RR    125  ABU DHABI      160.140       177.28     163.43
37    DC  PBKS    164      DUBAI      164.820       167.36     171.54
38   KKR   RCB     84  ABU DHABI      159.640       154.33     163.43
39    RR   SRH    154      DUBAI      169.570       152.81     171.54
40   CSK    MI    114    SHARJAH      160.140       155.37     177.36
41   KKR    DC    194  ABU DHABI      159.640       164.70     163.43
42  PBKS   SRH    126      DUBAI      169.860       152.81     171.54
43   RCB   CSK    145      DUBAI      157.670       162.50     171.54
44    MI    RR    195  ABU DHABI      181.250       177.28     163.43
45   KKR  PBKS    149    SHARJAH      159.640       167.36     177.36
46   SRH    DC    219      DUBAI      164.125       164.70     171.54
47   RCB    MI    164  ABU DHABI      157.670       155.37     163.43
48   KKR   CSK    172      DUBAI      159.640       162.50     171.54
49  PBKS    RR    185  ABU DHABI      169.860       177.28     163.43
50    DC    MI    110      DUBAI      164.820       155.37     171.54
51   RCB   SRH    120    SHARJAH      157.670       152.81     177.36
52  PBKS   CSK    153  ABU DHABI      169.860       162.50     163.43
53   KKR    RR    191      DUBAI      159.640       177.28     171.54
54   RCB    DC    152  ABU DHABI      157.670       164.70     163.43
55    MI   SRH    149    SHARJAH      181.250       152.81     177.36
56    MI    D

In [43]:
df_Mi = df_pr[df_pr["team1"] == "MI"]
df_Mi

team1 team2  runs1    stadium  batting_avg  bowling_avg  pitch_avg
0     MI   CSK    162  ABU DHABI       181.25       162.50     163.43
4     MI   KKR    195  ABU DHABI       181.25       157.57     163.43
12    MI  PBKS    191  ABU DHABI       181.25       167.36     163.43
16    MI   SRH    208    SHARJAH       181.25       152.81     177.36
19    MI    RR    193  ABU DHABI       181.25       177.28     163.43
35    MI  PBKS    176      DUBAI       181.25       167.36     171.54
44    MI    RR    195  ABU DHABI       181.25       177.28     163.43
55    MI   SRH    149    SHARJAH       181.25       152.81     177.36
56    MI    DC    200      DUBAI       181.25       164.70     171.54

In [44]:
import sklearn
from sklearn.linear_model import LinearRegression as lr
from sklearn.model_selection import train_test_split

In [54]:
x = df_pr.drop(columns=["runs1","team1",'team2','stadium'])
y = df_pr['runs1']

In [55]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=1)

In [56]:
model = lr()


In [57]:
model.fit(x_train,y_train)

LinearRegression()

In [58]:
model.predict(x_test)

array([171.2021481 , 154.77063333, 155.98781817, 165.1571544 ,
       166.88623877, 191.03353713])

In [59]:
y_test

39    154
41    194
2     163
48    172
50    110
44    195
Name: runs1, dtype: int64